name: build and push

on:
  push:
    branches:
    - master
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
    - uses: actions/checkout@v2

    - run: |
        git config --global user.name "imroc"
        git config --global user.email "roc@imroc.cc"
        git clone https://${USERNAME}:${PASSWORD}@gitee.com/imroc/istio-guide-book.git book
      env:
        USERNAME: '${{ secrets.GITEE_USERNAME }}'
        PASSWORD: '${{ secrets.GITEE_PASSWORD }}'

    - name: Setup mdBook
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: '0.4.15'

    - run: |
        mdbook build -d book/book
        cd book/book && git add . && git commit -m "update" && git push